// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200616215624_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bussiness_Logic.Models.Equipment", b =>
                {
                    b.Property<int>("Id_Equipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Equipement_Internal_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int?>("EquipmentTypeId_EquipmentType")
                        .HasColumnType("int");

                    b.Property<string>("Equipment_Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Equipment_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Equipment_Observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<string>("Equipment_SN")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("Equipment_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Equipment_TradeMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Equipment_Warranty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Equipment");

                    b.HasIndex("EquipmentTypeId_EquipmentType");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.EquipmentType", b =>
                {
                    b.Property<int>("Id_EquipmentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EquipmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id_EquipmentType");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Lending", b =>
                {
                    b.Property<int>("Id_Lending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DateLending")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionMantenaince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("UbicationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId_Users")
                        .HasColumnType("int");

                    b.HasKey("Id_Lending");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UbicationId");

                    b.HasIndex("UsersId_Users");

                    b.ToTable("Lendings");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Logs", b =>
                {
                    b.Property<int>("Id_Logs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersId_Users")
                        .HasColumnType("int");

                    b.HasKey("Id_Logs");

                    b.HasIndex("UsersId_Users");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Mantenaince", b =>
                {
                    b.Property<int>("Id_Mantenaince")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DateMantenaince")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionMantenaince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("StratusMantenaince")
                        .HasColumnType("bit");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id_Mantenaince");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UsersId");

                    b.ToTable("Mantenainces");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.ProviderType", b =>
                {
                    b.Property<int>("Id_ProviderType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProviderTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id_ProviderType");

                    b.ToTable("ProvidersType");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Providers", b =>
                {
                    b.Property<int>("Id_Providers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ProviderTypeId_ProviderType")
                        .HasColumnType("int");

                    b.Property<string>("TypeIdentification")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.HasKey("Id_Providers");

                    b.HasIndex("ProviderTypeId_ProviderType");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Purchase", b =>
                {
                    b.Property<int>("Id_Purchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("NumberInvoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ProvidersId")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseEvidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Purchase");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProvidersId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Ubication", b =>
                {
                    b.Property<int>("Id_Ubication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UbicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id_Ubication");

                    b.ToTable("Ubications");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Users", b =>
                {
                    b.Property<int>("Id_Users")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Id_UsersType")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("N_Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.Property<int?>("UserTypeId_UsersType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id_Users");

                    b.HasIndex("UserTypeId_UsersType");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.UsersType", b =>
                {
                    b.Property<int>("Id_UsersType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UsersTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id_UsersType");

                    b.ToTable("UsersType");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Equipment", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId_EquipmentType");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Lending", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.Equipment", "Equipments")
                        .WithMany("Lendings")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Logic.Models.Ubication", "Ubication")
                        .WithMany()
                        .HasForeignKey("UbicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Logic.Models.Users", "Users")
                        .WithMany("Lendings")
                        .HasForeignKey("UsersId_Users");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Logs", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId_Users");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Mantenaince", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.Equipment", "Equipments")
                        .WithMany("Mantenainces")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Logic.Models.Users", "Users")
                        .WithMany("Mantenainces")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Providers", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.ProviderType", "ProviderType")
                        .WithMany()
                        .HasForeignKey("ProviderTypeId_ProviderType");
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Purchase", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.Equipment", "Equipments")
                        .WithMany("Purchases")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bussiness_Logic.Models.Providers", "Providers")
                        .WithMany("Purchases")
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bussiness_Logic.Models.Users", b =>
                {
                    b.HasOne("Bussiness_Logic.Models.UsersType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId_UsersType");
                });
#pragma warning restore 612, 618
        }
    }
}
